# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.

# Basic Site Settings
locale                   : "en-US"
site_theme               : "default" # The available themes options are "default", "air", "sunrise", "mint", "dirt" and "contrast"
title                    : "Roshan Jha"
title_separator          : "-"
name                     : &name "Roshan Jha"
description              : &description "Roshan Jha's academic portfolio. Postdoctoral Researcher"
url                      : "https://zharoshan94.github.io" # Replace 'zharoshan94' with your actual GitHub username if different
baseurl                  : "" 
repository               : "zharoshan94/zharoshan94.github.io" # Replace with your actual GitHub username

# Site Author - The following control what appear as part of the author content on the side bar.
author:
  # Biographic information
  avatar           : "profile.png" # Place a professional photo named 'profile.png' in the 'images' folder
  name             : "Roshan Jha"
  # pronouns         : "he/him"  
  bio              : "Postdoctoral Research Fellow"
  location         : "United Kingdom"
  employer         : "University of St Andrews"
  uri              : "https://zharoshan94.github.io" 
  email            : "zharoshan94@gmail.com" 

  # Academic websites
  academic         : https://www.st-andrews.ac.uk/earth-sciences/people/rj90/
  arxiv            : 
  googlescholar    : https://scholar.google.com/citations?user=Cc8r3JMAAAAJ&hl=en
  inspire-hep      : 
  impactstory      : 
  orcid            : https://orcid.org/0000-0001-9068-4036
  semantic         : 
  ssrn             : 
  pubmed           : 
  researchgate     : 
  scopus           : 
  zotero           : 

  # Repositories and software development
  bitbucket        : 
  codepen          : 
  dribbble         : 
  github           : "zharoshan94"
  kaggle           :   
  stackoverflow    :     

  # Social media
  artstation       : 
  bluesky          : 
  facebook         : 
  flickr           : 
  foursquare       : 
  goodreads        : 
  google_plus      : 
  keybase          : 
  instagram        : 
  lastfm           : 
  linkedin         : "roshan-jha-nov94" # Based on your CV's in/roshan-jha link
  mastodon         : 
  medium           : 
  pinterest        : 
  soundcloud       : 
  steam            : 
  telegram         : 
  tumblr           : 
  twitter          : 
  vine             : 
  weibo            : 
  wikipedia        : 
  xing             : 
  youtube          : 
  zhihu            : 

# Publication Category - The following the list of publication categories and their headings
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'    
  conferences:
    title: 'Conference Papers'

# Site Settings
teaser                   :  
breadcrumbs              : false 
words_per_minute         : 160
future                   : true
read_more                : "disabled" 
talkmap_link             : false      
comments:
  provider               : 
  disqus:
    shortname            :
  discourse:
    server               : 
  facebook:
    appid                :
    num_posts            : 
    colorscheme          : 
staticman:
  allowedFields          : ['name', 'email', 'url', 'message']
  branch                 : "gh-pages" 
  commitMessage          : "New comment."
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "_data/comments/{options.slug}"
  requiredFields         : ['name', 'email', 'message']
  transforms:
    email                : "md5"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601" 
atom_feed:
  hide                   : false     
  path                   : 

# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Social Sharing
twitter:
  username               : &twitter
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 :  
og_description           :  
social:
  type                   : Person 
  name                   : Roshan Jha
  links: 

# Analytics
analytics:
  provider               :  "false" 
  google:
    tracking_id          :

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# These settings control the types of collections used by the template
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# These settings control how pages and collections are included in the site
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed 

# Outputting
permalink: /:categories/:title/
timezone: Etc/UTC 

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Mimic GitHub Pages with --safe
whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development 